# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trtl_local_block_explorer_UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1457, 852)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_1.sizePolicy().hasHeightForWidth())
        self.tab_1.setSizePolicy(sizePolicy)
        self.tab_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_1.setObjectName("tab_1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_blktx = QtWidgets.QHBoxLayout()
        self.horizontalLayout_blktx.setSpacing(3)
        self.horizontalLayout_blktx.setObjectName("horizontalLayout_blktx")
        self.verticalLayout_blk = QtWidgets.QVBoxLayout()
        self.verticalLayout_blk.setObjectName("verticalLayout_blk")
        self.label_rblk = QtWidgets.QLabel(self.tab_1)
        self.label_rblk.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_rblk.setObjectName("label_rblk")
        self.verticalLayout_blk.addWidget(self.label_rblk)
        self.tableWidget_blk = QtWidgets.QTableWidget(self.tab_1)
        self.tableWidget_blk.setObjectName("tableWidget_blk")
        self.tableWidget_blk.setColumnCount(0)
        self.tableWidget_blk.setRowCount(0)
        self.tableWidget_blk.verticalHeader().setVisible(False)
        self.verticalLayout_blk.addWidget(self.tableWidget_blk)
        self.horizontalLayout_blktx.addLayout(self.verticalLayout_blk)
        self.verticalLayout_tx = QtWidgets.QVBoxLayout()
        self.verticalLayout_tx.setObjectName("verticalLayout_tx")
        self.label_txpl = QtWidgets.QLabel(self.tab_1)
        self.label_txpl.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_txpl.setObjectName("label_txpl")
        self.verticalLayout_tx.addWidget(self.label_txpl)
        self.tableWidget_txPool = QtWidgets.QTableWidget(self.tab_1)
        self.tableWidget_txPool.setObjectName("tableWidget_txPool")
        self.tableWidget_txPool.setColumnCount(0)
        self.tableWidget_txPool.setRowCount(0)
        self.verticalLayout_tx.addWidget(self.tableWidget_txPool)
        self.horizontalLayout_blktx.addLayout(self.verticalLayout_tx)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_blktx)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("blocks.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_1, icon, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_search = QtWidgets.QHBoxLayout()
        self.horizontalLayout_search.setSpacing(7)
        self.horizontalLayout_search.setObjectName("horizontalLayout_search")
        self.verticalLayout_blksearch = QtWidgets.QVBoxLayout()
        self.verticalLayout_blksearch.setSpacing(3)
        self.verticalLayout_blksearch.setObjectName("verticalLayout_blksearch")
        self.textEdit_blk = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_blk.setObjectName("textEdit_blk")
        self.verticalLayout_blksearch.addWidget(self.textEdit_blk)
        self.tableWidget_blk_search = QtWidgets.QTableWidget(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget_blk_search.setFont(font)
        self.tableWidget_blk_search.setObjectName("tableWidget_blk_search")
        self.tableWidget_blk_search.setColumnCount(0)
        self.tableWidget_blk_search.setRowCount(0)
        self.verticalLayout_blksearch.addWidget(self.tableWidget_blk_search)
        self.lineEdit_blk = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_blk.setObjectName("lineEdit_blk")
        self.verticalLayout_blksearch.addWidget(self.lineEdit_blk)
        self.btn_blk = QtWidgets.QPushButton(self.tab_2)
        self.btn_blk.setObjectName("btn_blk")
        self.verticalLayout_blksearch.addWidget(self.btn_blk)
        self.horizontalLayout_search.addLayout(self.verticalLayout_blksearch)
        self.verticalLayout_txsearch = QtWidgets.QVBoxLayout()
        self.verticalLayout_txsearch.setSpacing(3)
        self.verticalLayout_txsearch.setObjectName("verticalLayout_txsearch")
        self.textEdit_tx = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_tx.setObjectName("textEdit_tx")
        self.verticalLayout_txsearch.addWidget(self.textEdit_tx)
        self.tableWidget_tx_search = QtWidgets.QTableWidget(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget_tx_search.setFont(font)
        self.tableWidget_tx_search.setObjectName("tableWidget_tx_search")
        self.tableWidget_tx_search.setColumnCount(0)
        self.tableWidget_tx_search.setRowCount(0)
        self.verticalLayout_txsearch.addWidget(self.tableWidget_tx_search)
        self.lineEdit_tx = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_tx.setObjectName("lineEdit_tx")
        self.verticalLayout_txsearch.addWidget(self.lineEdit_tx)
        self.btn_tx = QtWidgets.QPushButton(self.tab_2)
        self.btn_tx.setObjectName("btn_tx")
        self.verticalLayout_txsearch.addWidget(self.btn_tx)
        self.horizontalLayout_search.addLayout(self.verticalLayout_txsearch)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_search)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon1, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1457, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionAbout_TRTL_Local_Block_Explorer = QtWidgets.QAction(MainWindow)
        self.actionAbout_TRTL_Local_Block_Explorer.setObjectName("actionAbout_TRTL_Local_Block_Explorer")
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuHelp.addAction(self.actionAbout_TRTL_Local_Block_Explorer)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_rblk.setText(_translate("MainWindow", "Recent Block"))
        self.label_txpl.setText(_translate("MainWindow", "Transaction Pool"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Recent Blocks and Tx Pool"))
        self.btn_blk.setText(_translate("MainWindow", "Go to Block"))
        self.btn_tx.setText(_translate("MainWindow", "Find Transaction"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Search"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))
        self.actionAbout_TRTL_Local_Block_Explorer.setText(_translate("MainWindow", "About TRTL Local Block Explorer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

